backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
# publish_mode: editorial_workflow
media_folder: "assets/imgs/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "milestones"
    label: "Milestones"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "default",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Milestone Date", name: "milestonedate", widget: "date" }
      - label: "Milestone Type"
        name: "type"
        widget: "select"
        options:
          - { label: "Latest", value: "latest" }
          - { label: "Future", value: "future" }
          - { label: "Complete", value: "complete" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - label: "Files"
        required: false
        name: "files"
        widget: "list"
        summary: "{{fields.filename}}"
        fields:
          - { label: File, name: fileupload, widget: file }
          - { label: File Name, name: filename, widget: string }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          hint: "Leave this alone",
        }
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - label: "Project Hub"
        name: "hub"
        file: "index.md"
        fields:
          - {
              label: "Project Title",
              name: "title",
              widget: "string",
              default: "Jarvis, Mark 4 wraps lines",
            }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "default",
            }
          - {
              label: "Client Name",
              name: "clientname",
              widget: "string",
              default: "Marvel Studios",
            }
          - { label: "Client Logo", name: "clientlogo", widget: "image" }
          - { label: "Client Logo URL", name: "clienturl", widget: "string" }
          - label: "Quick Links"
            name: "quicklinks"
            widget: "list"
            types:
              - label: "Link"
                name: "quicklinks_link"
                widget: object
                summary: "{{fields.linktext}}"
                fields:
                  - { label: Link, name: link, widget: string }
                  - { label: Link Text, name: linktext, widget: string }
              - label: "File"
                name: "quicklinks_file"
                summary: "{{fields.linktext}}"
                widget: object
                fields:
                  - { label: File, name: fileupload, widget: file }
                  - { label: File Name, name: linktext, widget: string }
          - {
              label: "SF Logo Link",
              name: "sflink",
              widget: "string",
              default: "https://superfriendly.com/",
              required: false,
              hint: "Defaults to superfriendly.com.",
            }
